### ISSUE TITLE
Refactor keyboard capturing

### ISSUE THREAD

**Issue by almarklein** [vispy/jupyter_rfb#16]
Right now, if you hover over the widget, you cannot type into the code-input that is currently active. This keyboard capture thing is hard because an `<img>` cannot have focus.

A solution might be to add a 1x1 px `<a>` or `<input>` element that we give focus once the user clicks the `<img>`

**Comment by djhoese** [comment]
Can you give `div`s focus? Either way, sounds good.

**Comment by almarklein** [comment]
Nope, only specific ones, as it turns out.
