### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by almarklein** [vispy/jupyter_rfb#3]
## Aspects of performance

* Make sure not to spam the client. We've implemented this from the start with a feedback mechanism.
* Prevent unnecessary drawing. Implemented in #43.
* Reduce image encoding and decoding time (what this issue focuses the most on). Implemented in #45.
* Reduce image io time, by reducing byte-size of the encoded image. This is less relevant on localhost, but plays a more significant role when the server is remote. The type of image encoding influences this.
* More general, reduce the time from the generation of the image to its display.

## Ideas to improve performance

* Use a faster PNG encoder.
* Encode images as JPEG (via pillow and/or simplejpeg).
* Look into rate limiting strategies like diff pngs (pixels that do not change have alpha 0).
* Use an mpeg4 stream.

### Our pure Python PNG implementation is pretty darn fast

It's faster than that of Pillow. It uses the zlib library and the rest is producing a header and put things together.

### Performance with PNG encoding varies with the content of the image

Images that contain more entropy (more random data) are harder to compress for PNG. This means it takes longer (more CPU) to compress, and also produces larger blobs (more IO time). The latter can be expected from a lossless format. It is somewhat surprising is that the encoding time increases significantly. As a consequence, with PNG encoding the experienced smoothness depends on what is being rendered, which is not a great feature.

### JPEG encoding has a lot of nice properties

Pros:
* It encodes much faster then PNG. Browsers can also decode it very fast.
* It produces significantly smaller blobs.
* Lowering the quality both reduces the encoding time and the size of the blob.
* The encode time does not scale as much with entropy as it does with PNG.
* It's very easy to implement (only changes at the server).

It also has downsides:
* It's lossy.
* No alpha channel.

### Using an mpeg4 stream is hard

Details in #44.

### Using diffs can be interesting but I decided not to pursue this further

Using diffs is an interesting approach to improve performance. The idea is to define keyframes every `n` seconds and for the next frames detect what pixels have changed relative to the keyframe. The pixels that have not changed are set to all zeros (color and alpha). In the browser you have two `<img>` elements atop each-other; the keyframe and the diff on top.

If only a fraction of the data has changed, this means most pixels in the diff image will be all zero, which will result in a very fast compression and a very small blob. Therefore this can potentially be a huge win.

However, this method is bound to using PNG encoding (JPEG does not have alpha) and therefore you inherit its downsides. You'd need quite a large percentage of static pixels to catch up with the performance of JPEG. Worst case, all pixels change and there is no benefit - you even do extra work to calculate the diff.

I can see how this approach can work well for plotting-data (a white background with some lines, markers, etc). But I expect that for anything else it cannot compete with JPEG. 

## Conclusion

We went for JPEG encoding, and always sending a PNG when the interaction has stopped. See #45

**Comment by almarklein** [comment]
I've done some testing with this code:

```py
import io
import time
import numpy as np
from jupyter_rfb._png import array2png
import PIL.Image

        
def array2png_pillow(img_array):
    assert img_array.dtype == np.uint8
    img_pil = PIL.Image.fromarray(img_array)
    f = io.BytesIO()
    img_pil.save(f, format="PNG")
    return f.getvalue()


def array2jpg(img_array, quality=90):
    assert img_array.dtype == np.uint8
    img_pil = PIL.Image.fromarray(img_array)
    f = io.BytesIO()
    img_pil.save(f, format="JPEG", quality=quality)
    return f.getvalue()


# Create an image
entropy = 10
n = 2000
im = np.random.randint(0, 255, (n, n, 3))
im = (im / entropy).astype(np.uint8) * entropy

# PNG conversion in pure Python
t0 = time.perf_counter()
bb = array2png(im)
t1 = time.perf_counter()
print(f"PNG pure Pythone took {t1-t0:0.2f}s - {len(bb)/1024:0.1f}kiB" )

# PNG conversion with Pillow
t0 = time.perf_counter()
bb = array2png_pillow(im)
t1 = time.perf_counter()
print(f"PNG with Pillow took {t1-t0:0.2f}s - {len(bb)/1024:0.1f}kiB" )

# JPEG conversion with Pillow, quality 90
t0 = time.perf_counter()
bb = array2jpg(im, 90)
t1 = time.perf_counter()
print(f"JPEG with Pillow took {t1-t0:0.2f}s - {len(bb)/1024:0.1f}kiB" )

# JPEG conversion with Pillow, quality 20
t0 = time.perf_counter()
bb = array2jpg(im, 20)
t1 = time.perf_counter()
print(f"JPEG with Pillow low quality took {t1-t0:0.2f}s - {len(bb)/1024:0.1f}kiB" )
```

Observations so far (I may update later):
* The pure Python PNG approach is faster than writing PNG with Pillow.
* Converting to JPEG is ~10x faster than converting to PNG, and results in 2x smaller blobs.
* Using a lower JPEG compression is faster still, and produces still smaller blobs. Could be a nice knob to turn.

I plan to look into diffs as well, which only work with PNG (JPEG does not have an alpha channel). But so far I'm quite enthusiastic about using Pillow JPEG's :)

**Comment by djhoese** [comment]
There isn't really a benefit to an alpha channel right? The typical use is on a browser where I would think the user wouldn't want a transparency to the jupyter notebook background color, right? I suppose if you took a screenshot maybe you might want an alpha band, but I'm not sure that would happen often. Maybe make this something the user can control?

Any idea if certain browsers perform differently for these different formats? I would think not in a meaningful way in this day and age.

**Comment by almarklein** [comment]
With my comment about the alpha channel I meant that you can use it to create keyframes and then diffs based on it. This can help reduce the size of the image.My feeling is that its quite a bit more work (more CPU load), but I want to at least investigate it a bit.

> Any idea if certain browsers perform differently for these different formats? 

I have yet to test that - for now I have only looked at the encoding step, though that part is certainly a bottleneck.

**Comment by almarklein** [comment]
I've briefly looked into mp4 encoding, but apart from needing something like a dependency on ffmpeg or something, we'd have to setup a stream (via a websocket?) to make it work. I don't think I want to go there.

**Comment by djhoese** [comment]
Nice job on the tests. I think choosing the format should always be something the user can control. There is always someone who wants lossless versus lossy compression.

> I've briefly looked into mp4 encoding, but apart from needing something like a dependency on ffmpeg or something, we'd have to setup a stream (via a websocket?) to make it work. I don't think I want to go there.

I think in one of the original vispy issues that resulted in this project I brought up some existing jupyter widget library that does this kind of video streaming. Might be something to look at.

**Comment by almarklein** [comment]
> There is always someone who wants lossless versus lossy compression.

I agree.

> [...] some existing jupyter widget library that does this kind of video streaming

I think you mean this: https://github.com/maartenbreddels/ipywebrtc

From what I understand, this leverages the webrtc API in the browser, afaik it cannot do video encoding in Python - but I'd love to be proven wrong on that.

**Comment by djhoese** [comment]
Ah I think you're right. There is probably something that could be adopted with this "MediaStream" idea: https://ipywebrtc.readthedocs.io/en/v0.6.0/WidgetStream.html

But yeah it doesn't do the actual encoding for you. Assuming jpeg is the default, what if ffmpeg was installed and you used something like imageio-ffmpeg or https://kkroening.github.io/ffmpeg-python/? What does the frontend look like? What does the code look like? How are mouse events handled on a video element on the browser?

**Comment by almarklein** [comment]
I don't think the front-end would be complicated. Worst case we put an invisible div in front of the `<video>` to capture mouse events. The server-side and the IO will be the hard part. I wrote some thoughts up in #44.

**Comment by almarklein** [comment]
I added a section about subrectangles, an approach somewhat similar to diff images, but that can be based on JPEG, and therefore might be something that we can add to what we have now.

**Comment by almarklein** [comment]
@tschoy Good point. We've killed that use-case right now. Could you please create a new issue for this, to discuss this further?
