### ISSUE TITLE
Support for VSCode

### ISSUE THREAD

**Issue by Korijn** [vispy/jupyter_rfb#53]
In VSCode the notebooks are not interactive:

![image](https://user-images.githubusercontent.com/1882046/145003243-dbb1088e-5a4e-4601-80a3-e213befd20f2.png)

![image](https://user-images.githubusercontent.com/1882046/145003296-11dd853f-a839-4c87-a5b3-617b62c78e03.png)

(Running examples from https://github.com/pygfx/wgpu-py/pull/202)

**Comment by almarklein** [comment]
Are jupyter widgets supposed to work in Code? I get `Error loading preloads: Could not find renderer`

**Comment by almarklein** [comment]
Ok, it's working now.

I can reproduce that only the "initial snapshot is shown". And I can fix this by disabling our `_repr_mimebundle_` logic. That produces a working output, except that the sizing does not work: the widgets are huge and can only be resized manually.

So I think we can make this work, but it will require some work.
