### ISSUE TITLE
kernel dies if widget is resized to a very large height, this sometimes happens unintentionally

### ISSUE THREAD

**Issue by kushalkolar** [vispy/jupyter_rfb#62]
This is a bizarre issue that seems to happen if the widget is left unattended for a long period of time (~30+ minutes?) . If you then try to resize it after this long unattended period it elongates vertically downward extremely fast, as if I suddenly increased my mouse cursor speed by an order of magnitude. The kernel then crashes. 

I'll try to reproduce and provide more info soon.

**Comment by almarklein** [comment]
Interesting ... 😕

**Comment by almarklein** [comment]
The latest changes did change some stuff related to the sizing, so with a bit of luck this is now fixed ... ?

**Comment by almarklein** [comment]
I tried, but I have not yet been able to reproduce this. I tried to mimic your example by putting a simple canvas inside an hbox and vbox, but no luck yet.

Would it be possible to provide a minimal example for which the effect happens on your machine? E.g. does it also happen with the hello world example of jupyter_rfb? Does it only happen when embedded in ipywidgets? Or does it only happen with a fastplotlib Plot?

**Comment by kushalkolar** [comment]
I just tried playing with this more:

1. The auto-scroll behavior isn't always triggered, I can't seem to figure out exactly what triggers it. 
2. If you resize the RFB widget while scrolling fast:
    - the hello world example doesn't cause the kernel to die
    - simple pygfx example (shown below) does cause the kernel to die

```python
import pygfx
import numpy
from wgpu.gui.auto import WgpuCanvas

canvas = WgpuCanvas()
renderer = pygfx.WgpuRenderer(canvas)

a = numpy.random.rand(512, 512).astype(numpy.float32)

tex = pygfx.Texture(a, dim=2).get_view()
geo = pygfx.Geometry(grid=tex)
mat = pygfx.ImageBasicMaterial(clim=(0, 1))

img = pygfx.Image(geo, mat)

cam = pygfx.OrthographicCamera(512, 512)
cam.position.set(256, 256, 1)

scene = pygfx.Scene()
scene.add(img)

canvas.request_draw(lambda: renderer.render(scene, cam))

canvas
```

**Comment by almarklein** [comment]
Still can't replicate it, but this should do the trick: #70.
