### ISSUE TITLE
Compatible version for ipywidget 8 

### ISSUE THREAD

**Issue by skapin** [vispy/jupyter_rfb#63]
Hi, i have made change on my side to make a working version for ipywidget 8

I have pushed a conda version here and i will push a PR here when I can and after more test

https://anaconda.org/eshard/jupyter_rfb

**Comment by skapin** [comment]
https://github.com/vispy/jupyter_rfb/pull/64

**Comment by almarklein** [comment]
Closed via #64. Thanks again!
