### ISSUE TITLE
Can `jupyter_rfb` work inside Google Colab?

### ISSUE THREAD

**Issue by jeertmans** [vispy/jupyter_rfb#95]
Hello,

I'm using `jupyter_rfb` to run interactive VisPy canvas inside Notebooks, and I'd like users to be able to run my code inside Google Colab. However, I cannot make it work (though I am using `Xvfb`), and I was wondering if any of you had a clue about this?

**Comment by jeertmans** [comment]
Never mind, closing as this is a duplicate of #57

**Comment by kushalkolar** [comment]
I tried this last year, there is something weird about google colab which makes the performance very poor #77

Similarly, I also tried it in regular jupyter lab a while ago on Google cloud engine and performance was also very poor, on servers near me. I've had good experience with Lambda cloud and Code Ocean though.

**Comment by jeertmans** [comment]
> I tried this last year, there is something weird about google colab which makes the performance very poor #77
> 
> Similarly, I also tried it in regular jupyter lab a while ago on Google cloud engine and performance was also very poor, on servers near me. I've had good experience with Lambda cloud and Code Ocean though.

Thanks for commenting @kushalkolar, I'll closely the evolution of related issues, and I hope that they will hopefully address them one day :'-)
